name: release

on:
  workflow_dispatch:
    inputs:
      options:
        description:
          Addional arguments send to nx release, if empty uses conventional-commits.
          https://nx.dev/nx-api/nx/documents/release
        type: string
        required: false

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: yarn install --immutable
      - name: Nx release
        run: yarn nx release --skip-publish ${{ github.event.inputs.options }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn nx run-many -t build
      - name: Nx release
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          yarn nx release publish ${{ github.event.inputs.options }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
